In [5]:
import numpy as np    # Numeric and matrix computation
import pandas as pd   # Optional: good package for manipulating data 
import sklearn as sk  # Package with learning algorithms implemented
import sklearn                         # Sklearn
from sklearn.model_selection import train_test_split, GridSearchCV # split
from sklearn.ensemble import BaggingClassifier
from sklearn.model_selection import cross_val_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn import preprocessing      # Preprocessing

## Hecho por Hasnain Shafqat

**Read CSV**

In [6]:
df = pd.read_csv("preprocessed_mean.csv");
df = pd.get_dummies(df, columns=["mode","key"])

targetCol = 'music_genre';
Y = df[targetCol]
X = df.drop([targetCol],axis=1)

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, shuffle=True, random_state=33)

df.shape


(20000, 26)

**Bagging with KNN**

In [7]:
scaler = preprocessing.Normalizer().fit(X_train)
X_train_norm = scaler.transform(X_train)
X_test_norm = scaler.transform(X_test)

In [8]:
cv= 10
params = {'n_estimators': [1,2,5,10,20,50,100,200, 250, 300, 350, 400]}

Baggingknn = BaggingClassifier(base_estimator= KNeighborsClassifier(metric = 'manhattan', n_neighbors = 20, weights = 'distance'))

gridBaggingknn = GridSearchCV(Baggingknn, params, cv=cv, n_jobs=-1)
gridBaggingknn.fit(X_train_norm,Y_train)
score_knn = gridBaggingknn.score(X_test_norm, Y_test)
print(score_knn)
print(gridBaggingknn.best_params_)

0.721
{'n_estimators': 350}


**Bagging with Decision Trees**

In [12]:
cv= 10
params = {'n_estimators': [1,2,5,10,20,50,100,200, 250, 300, 350, 400]}

Bagging = BaggingClassifier(base_estimator=DecisionTreeClassifier())

gridBagging = GridSearchCV(Bagging, params, cv=cv, n_jobs=-1)
gridBagging.fit(X_train,Y_train)
score_bagging = gridBagging.score(X_test, Y_test)
print(score_bagging)
print(gridBagging.best_params_)

0.89875
{'n_estimators': 300}


In [15]:
B1 = BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=300)
B1.fit(X_train,Y_train)
score_bf1 = B1.score(X_test, Y_test)
print(f"Accuray with 300 estimators {score_bf1}")

Accuray with 300 estimators 0.8975


In [14]:
cv= 10
params = {'n_estimators': [ x for x in range(275, 325, 5)]}

Bagging = BaggingClassifier(base_estimator=DecisionTreeClassifier())

gridBagging2 = GridSearchCV(Bagging, params, cv=cv, n_jobs=-1)
gridBagging2.fit(X_train,Y_train)
score_bagging_2 = gridBagging2.score(X_test, Y_test)
print(score_bagging_2)
print(gridBagging2.best_params_)

0.89975
{'n_estimators': 315}


In [20]:
B2 = []
B2 = BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators=315)
B2.fit(X_train,Y_train)
score_bf2 = B2.score(X_test, Y_test)
print(f"Accuray with 315 estimators {score_bf2}")

Accuray with 315 estimators 0.899


In [21]:
if score_bf1 > score_bf2:
    print("Model with 300 estimators is better")
else:
    print("Model with 315 estimators is better")

Model with 315 estimators is better


In [22]:
knBagging = BaggingClassifier(base_estimator=DecisionTreeClassifier(), n_estimators = 315)
knBagging.fit(X_train, Y_train)
pred=knBagging.predict(X_test)
print("\nConfusion matrix on test set:\n",sk.metrics.confusion_matrix(Y_test, pred))


Confusion matrix on test set:
 [[903  46   1   5]
 [ 17 940  42  58]
 [  1  16 888  90]
 [ 10  30  91 862]]


In [23]:
Y_test_pred = knBagging.predict(X_test);
print(sklearn.metrics.classification_report(Y_test,Y_test_pred))

              precision    recall  f1-score   support

   Classical       0.97      0.95      0.96       955
  Electronic       0.91      0.89      0.90      1057
     Hip-Hop       0.87      0.89      0.88       995
        Rock       0.85      0.87      0.86       993

    accuracy                           0.90      4000
   macro avg       0.90      0.90      0.90      4000
weighted avg       0.90      0.90      0.90      4000

